name: Automatically create reports for AliPhysics / O2

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '32 * * * *'

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: octokit/graphql-action@v2.x
      id: get_latest_releases
      with:
        query: |
              {
                repository(name: "AliPhysics", owner: "alisw") {
                  releases(last:10) {
                    edges {
                      node {
                        tagName
                        publishedAt
                      }
                    }
                  }
                }
              }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: octokit/graphql-action@v2.x
      id: get_latest_o2_prs
      with:
        query: |
              {
                repository(name: "AliceO2", owner: "AliceO2Group") {
                  pullRequests(last: 100) {
                    edges {
                      node {
                        state
                        mergedAt
                        title
                        author {
                          login
                        }
                        files(last: 100) {
                          edges {
                            node {
                             path
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update README
      run: |
        cat <<\EOF > README.md
        ## Recent releases to AliPhysics
        EOF
        cat <<\EOF > releases.json
        ${{ steps.get_latest_releases.outputs.data }}
        EOF
        cat <<\EOF > o2_prs.json
        ${{ steps.get_latest_o2_prs.outputs.data }}
        EOF
        cat releases.json | jq -r ".repository.releases.edges[].node | select(.publishedAt > \"$(date -v -8d +%Y-%m-%d)\") | \"- \(.tagName): Done on \(.publishedAt | split(\"T\")[0]).\"" >> README.md
        for x in Algorithm Analysis Common DataFormats Detectors EventVisualisation Examples Framework Generators Steer Testing Utilities; do
          cat o2_prs.json | jq ".repository.pullRequests.edges[].node | select(.files.edges[].node.path | test(\"$x\")) | del(.files) | select(.state == \"MERGED\" and .mergedAt >= \"$(date -v -7d +%Y-%m-%d)\")" > $x_prs.json
          if [ ! X`jq -s length $x_prs.json` = X0 ]; then 
            cat <<EOF >> README.md
        ## Recent developments in O2 - $x
        EOF
            cat $x_prs.json | jq -r '"- \(.mergedAt | split("T")[0]) @\(.author.login): \(.title)"' | sort -u >> README.md
          fi
        done
        cat README.md
    - name: Commit and push if changed
      run: |-
        git add .
        git diff
        git config --global user.email "github-action-bot@example.com"
        git config --global user.name "GitHub Action Bot"
        git commit -m "Updated README" -a || echo "No changes to commit"
        git push
